---
- name: Install Docker on Ubuntu
  hosts: all
  become: yes
  tasks:

    # Download Docker GPG key manually
    - name: Download Docker GPG key manually
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | tee /etc/apt/trusted.gpg.d/docker.asc

    # Add Docker's official repository to apt sources
    - name: Add Docker apt repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable'
        state: present
        filename: 'docker'

    # Update apt cache
    - name: Update apt cache
      apt:
        update_cache: yes

    # Install Docker
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    # Start and enable Docker service
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user ubutu to Docker groupi
      shell: |     
        usermod -aG docker ubuntu
